package com.job5156.core.common.option;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import org.apache.commons.lang.StringUtils;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class OptionPositionMap {

    public final static Map<Integer, Map<String, String>> OPT_MAP_POSITION = new LinkedHashMap<>();
    public  static Map<Integer,List<Map<String,String>>>  OPT_MAP_BIG_SMALL_CITY  =null;//保大类以及其下小类的对应关系
    public static List<Map<String,String>> OPT_LIST_BIG  =null;//保存所有大类

	static {
        OPT_MAP_POSITION.put(1000,OptionMap.setMap("计算机开发/应用类","InformationTechnology","computer"));
        OPT_MAP_POSITION.put(1001,OptionMap.setMap("网络工程师","Network Engineering","network"));
        OPT_MAP_POSITION.put(1002,OptionMap.setMap("网络信息安全工程师","Information Security Engineer","security"));
        OPT_MAP_POSITION.put(1003,OptionMap.setMap("数据库开发与管理（DBA）","Database Administrator","dba"));
        OPT_MAP_POSITION.put(1004,OptionMap.setMap("数据库系统工程师","Database System Engineer","dsner"));
        OPT_MAP_POSITION.put(1005,OptionMap.setMap("系统分析师/系统分析员","System Analyst","analyst"));
        OPT_MAP_POSITION.put(1006,OptionMap.setMap("系统维护员","System maintenace","maintenace"));
        OPT_MAP_POSITION.put(1007,OptionMap.setMap("系统测试师","System Testing QA","tqa"));
        OPT_MAP_POSITION.put(1008,OptionMap.setMap("系统/网络管理员","System/Network Administrator","administrator"));
        OPT_MAP_POSITION.put(1009,OptionMap.setMap("MRP/ERP/SAP实施工程师","Mrp/Erp/Actualize Engineering","mrp"));
        OPT_MAP_POSITION.put(1010,OptionMap.setMap("互联网软件开发工程师","Internet/E-Commerce Software Engineer","esoftner"));
        OPT_MAP_POSITION.put(1011,OptionMap.setMap("多媒体/游戏开发工程师","Multimedia/Game Development Engineer","gamener"));
        OPT_MAP_POSITION.put(1012,OptionMap.setMap("INTERNET/WEB/电子商务师","Internet/Web/E-Commerce","internet"));
        OPT_MAP_POSITION.put(1013,OptionMap.setMap("计算机辅助设计工程师","Computer Aided Designer Engineer","aidedner"));
        OPT_MAP_POSITION.put(1014,OptionMap.setMap("软件设计师","Software Designer","sdesigner"));
        OPT_MAP_POSITION.put(1015,OptionMap.setMap("软件工程师","Software Engineering","softwarener"));
        OPT_MAP_POSITION.put(1016,OptionMap.setMap("软件测试师","Software Testing QA","softtqa"));
        OPT_MAP_POSITION.put(1017,OptionMap.setMap("硬件测试师","Hardware Testing QA","hardtqa"));
        OPT_MAP_POSITION.put(1018,OptionMap.setMap("硬件工程师","Hardware Engineering","hardwarener"));
        OPT_MAP_POSITION.put(1019,OptionMap.setMap("网页设计师","Webpage Designer","webdner"));
        OPT_MAP_POSITION.put(1020,OptionMap.setMap("网页策划师","Web Designer","webplan"));
        OPT_MAP_POSITION.put(1021,OptionMap.setMap("网站编辑员","Website Editor","webeditor"));
        OPT_MAP_POSITION.put(1022,OptionMap.setMap("电脑美工","Computer Art Designer","artder"));
        OPT_MAP_POSITION.put(1023,OptionMap.setMap("栏目主持人","Column Emcee","emcee"));
        OPT_MAP_POSITION.put(1024,OptionMap.setMap("网站客服/SEO/淘宝美工","Website Customer Service / SEO / Taobao art","customer"));
        OPT_MAP_POSITION.put(1099,OptionMap.setMap("其它","Other","other"));
        OPT_MAP_POSITION.put(1100,OptionMap.setMap("计算机管理/技术支持类","InformationTechnology","support"));
        OPT_MAP_POSITION.put(1101,OptionMap.setMap("信息系统监理/信息系统项目管理","Management information systems Division/Information systems project management Division","information"));
        OPT_MAP_POSITION.put(1102,OptionMap.setMap("信息技术经理/主管","IT Manager/Supervisor","supervisor"));
        OPT_MAP_POSITION.put(1103,OptionMap.setMap("信息技术专员","IT Specialist","specialist"));
        OPT_MAP_POSITION.put(1104,OptionMap.setMap("信息分析师","IT Analyst","analyst"));
        OPT_MAP_POSITION.put(1105,OptionMap.setMap("系统集成/技术支持","System integration, Technical Support","integration"));
        OPT_MAP_POSITION.put(1106,OptionMap.setMap("标准化工程师","Standardization Engineer","seeng"));
        OPT_MAP_POSITION.put(1107,OptionMap.setMap("技术助理","Technical Assistant","technical"));
        OPT_MAP_POSITION.put(1108,OptionMap.setMap("项目总监","Project Director","pjdirector"));
        OPT_MAP_POSITION.put(1109,OptionMap.setMap("项目经理/项目主管","Project Manager","pjmanager"));
        OPT_MAP_POSITION.put(1110,OptionMap.setMap("项目执行/协调人员","Project Specialist/Coordinator","pjcoordinator"));
        OPT_MAP_POSITION.put(1111,OptionMap.setMap("技术总监CTO","Tech. Majordomo, Cto","cto"));
        OPT_MAP_POSITION.put(1112,OptionMap.setMap("信息主管/CIO","Information Majordomo/Cio","cio"));
        OPT_MAP_POSITION.put(1113,OptionMap.setMap("网络营运经理/主管","Web Operataions Manager/Supervisor","operataions"));
        OPT_MAP_POSITION.put(1199,OptionMap.setMap("其它","Other","other"));
        OPT_MAP_POSITION.put(1200,OptionMap.setMap("通讯类","Telecommunication","tele"));
        OPT_MAP_POSITION.put(1201,OptionMap.setMap("数据通信工程师","Data communication Engineer","dataner"));
        OPT_MAP_POSITION.put(1202,OptionMap.setMap("移动通信工程师","Mobile communication Engineer","mobiler"));
        OPT_MAP_POSITION.put(1203,OptionMap.setMap("通信技术工程师","Communication Engineer","communer"));
        OPT_MAP_POSITION.put(1204,OptionMap.setMap("有线传输工程师","Wired Transmission Engineer","wtener"));
        OPT_MAP_POSITION.put(1205,OptionMap.setMap("无线通信工程师","Wireless Communication Engineer","wcener"));
        OPT_MAP_POSITION.put(1206,OptionMap.setMap("电信交换工程师","Telecommunication Exchange Engineer","teener"));
        OPT_MAP_POSITION.put(1207,OptionMap.setMap("电信网络工程师","Telecommunication Network Engineer","tnener"));
        OPT_MAP_POSITION.put(1208,OptionMap.setMap("通信电源工程师","Communication Power Supply Engineer","cpsner"));
        OPT_MAP_POSITION.put(1209,OptionMap.setMap("射频工程师","Radio Frequency Engineer","rfener"));
        OPT_MAP_POSITION.put(1210,OptionMap.setMap("手机硬件项目经理","Mobile Hardware Manager","mobilehma"));
        OPT_MAP_POSITION.put(1211,OptionMap.setMap("手机软件项目经理","Mobile Software Manager","mobilesma"));
        OPT_MAP_POSITION.put(1212,OptionMap.setMap("手机应用开发工程师","Mobile Application Developer Engineer","mobileadner"));
        OPT_MAP_POSITION.put(1213,OptionMap.setMap("手机驱动/测试工程师","Mobile Driver Development/Test Engineer","mobileddner"));
        OPT_MAP_POSITION.put(1214,OptionMap.setMap("手机维修","Mobile Maintenance Engineer","mobilemner"));
        OPT_MAP_POSITION.put(1215,OptionMap.setMap("手机结构工程师","Mobile Structural Engineer","mobilesner"));
        OPT_MAP_POSITION.put(1299,OptionMap.setMap("其它","Other","other"));
        OPT_MAP_POSITION.put(1300,OptionMap.setMap("电子/电器（气）类","Electronics","electronics"));
        OPT_MAP_POSITION.put(1301,OptionMap.setMap("电子工程师/技术员","Electron Engineer","electronner"));
        OPT_MAP_POSITION.put(1302,OptionMap.setMap("电气工程师/技术员","Electric Engineer","electricner"));
        OPT_MAP_POSITION.put(1303,OptionMap.setMap("电器工程师","Electric apparatus Engineer","eleaner"));
        OPT_MAP_POSITION.put(1304,OptionMap.setMap("电力工程师","Electric power Engineer","elepner"));
        OPT_MAP_POSITION.put(1305,OptionMap.setMap("电子测试工程师","Electronic Test Engineer","eletner"));
        OPT_MAP_POSITION.put(1306,OptionMap.setMap("电路（布线）设计工程师","Circuit Design","circuit"));
        OPT_MAP_POSITION.put(1307,OptionMap.setMap("智能大厦/综合布线/弱电","Intelligent mansion/synthetic disposal/Weak electronic","eleweak"));
        OPT_MAP_POSITION.put(1308,OptionMap.setMap("自动控制技术员","Autocontrol","autocontrol"));
        OPT_MAP_POSITION.put(1309,OptionMap.setMap("无线电技术员","Radio-technology","radio"));
        OPT_MAP_POSITION.put(1310,OptionMap.setMap("半导体技术员","Semiconductor Technology","semic"));
        OPT_MAP_POSITION.put(1311,OptionMap.setMap("变压器/磁电工程师","Magnetoelectricity Engineer","magnetoner"));
        OPT_MAP_POSITION.put(1312,OptionMap.setMap("电声/音响工程师/技术员","Electric sound Engineer","elesoundner"));
        OPT_MAP_POSITION.put(1313,OptionMap.setMap("集成电路/芯片开发工程师","Integrated circuit/Chip development Engineer","chipner"));
        OPT_MAP_POSITION.put(1314,OptionMap.setMap("电子元器件工程师","Electronic primary device Engineer","elepdner"));
        OPT_MAP_POSITION.put(1315,OptionMap.setMap("电子声像设备","Electronic acoustic image equipment","eleaiener"));
        OPT_MAP_POSITION.put(1316,OptionMap.setMap("电池/电源开发工程师","Battery/Power source Development Engineer","battery"));
        OPT_MAP_POSITION.put(1317,OptionMap.setMap("嵌入式/底层软件开发（Linux/单片机/DSP/...）","Embedded/SCM/DSP/FPGA Development","scm"));
        OPT_MAP_POSITION.put(1318,OptionMap.setMap("光源与照明工程","Lamp-house and Lighting Engineering","lamp"));
        OPT_MAP_POSITION.put(1319,OptionMap.setMap("灯饰研发工程师","Lamp Development Engineer","lampdner"));
        OPT_MAP_POSITION.put(1320,OptionMap.setMap("电气维修员","Electric Maintain","maintain"));
        OPT_MAP_POSITION.put(1321,OptionMap.setMap("家用电器开发工程师","Household electric Appliances","appliances"));
        OPT_MAP_POSITION.put(1322,OptionMap.setMap("小家电","Small Household electric appliances","small"));
        OPT_MAP_POSITION.put(1323,OptionMap.setMap("数码产品开发工程师","Digital Production Development Engineer","digital"));
        OPT_MAP_POSITION.put(1324,OptionMap.setMap("产品研发工程师","Production Development Engineer","pd"));
        OPT_MAP_POSITION.put(1325,OptionMap.setMap("PCB工程师","PCB Engineer","pcb"));
        OPT_MAP_POSITION.put(1326,OptionMap.setMap("ARM开发工程师","ARM Development Engineer","arm"));
        OPT_MAP_POSITION.put(1327,OptionMap.setMap("MCU底层开发工程师","MCU Development Engineer","mcu"));
        OPT_MAP_POSITION.put(1328,OptionMap.setMap("FAE工程师","FAE Engineer","fae"));
        OPT_MAP_POSITION.put(1399,OptionMap.setMap("其它","Other","other"));
        OPT_MAP_POSITION.put(1400,OptionMap.setMap("销售管理类","Sales","sales"));
        OPT_MAP_POSITION.put(1401,OptionMap.setMap("销售总监","Sales Majordomo","xszj"));
        OPT_MAP_POSITION.put(1402,OptionMap.setMap("销售工程师","Sales engineer","xsgcs"));
        OPT_MAP_POSITION.put(1403,OptionMap.setMap("销售部经理","Sales Manager","xsjl"));
        OPT_MAP_POSITION.put(1404,OptionMap.setMap("销售主管","Sales Director","xszg"));
        OPT_MAP_POSITION.put(1405,OptionMap.setMap("销售助理","Sales Assistant","xszl"));
        OPT_MAP_POSITION.put(1406,OptionMap.setMap("渠道经理","Channel Manager","qdjl"));
        OPT_MAP_POSITION.put(1407,OptionMap.setMap("渠道主管","Channel Director","qdjl"));
        OPT_MAP_POSITION.put(1408,OptionMap.setMap("分销经理","Distribution Manager","fxjl"));
        OPT_MAP_POSITION.put(1409,OptionMap.setMap("区域销售经理","District Sales Manager","qyjl"));
        OPT_MAP_POSITION.put(1410,OptionMap.setMap("商务经理","Commerce Manager","swjl"));
        OPT_MAP_POSITION.put(1411,OptionMap.setMap("商务专员","Commerce Clerk","swzr"));
        OPT_MAP_POSITION.put(1412,OptionMap.setMap("商务助理","Business Assistant","swzl"));
        OPT_MAP_POSITION.put(1499,OptionMap.setMap("其它","Other","other"));
        OPT_MAP_POSITION.put(1500,OptionMap.setMap("销售业务类","Sales","sales"));
        OPT_MAP_POSITION.put(1501,OptionMap.setMap("销售代表","Sales Representative","xsdb"));
        OPT_MAP_POSITION.put(1502,OptionMap.setMap("客户代表","Customer Representative","customer"));
        OPT_MAP_POSITION.put(1503,OptionMap.setMap("业务员","Clerk","clerk"));
        OPT_MAP_POSITION.put(1504,OptionMap.setMap("推（营）销员","Salesman","salesman"));
        OPT_MAP_POSITION.put(1505,OptionMap.setMap("渠道/分销专员","Channel/Retails special Commissioner","retails"));
        OPT_MAP_POSITION.put(1506,OptionMap.setMap("经销商","Dealer","dealer"));
        OPT_MAP_POSITION.put(1599,OptionMap.setMap("其它","Other","other"));
        OPT_MAP_POSITION.put(1600,OptionMap.setMap("客户服务类","Customer Services","customers"));
        OPT_MAP_POSITION.put(1601,OptionMap.setMap("客户服务","Customer Service","cuss"));
        OPT_MAP_POSITION.put(1602,OptionMap.setMap("售前/售后服务/技术支持","Technical Support","tech"));
        OPT_MAP_POSITION.put(1603,OptionMap.setMap("投诉处理","Complains Solve","solve"));
        OPT_MAP_POSITION.put(1604,OptionMap.setMap("客户关系管理","Customer Relationship Administrator","relationship"));
        OPT_MAP_POSITION.put(1605,OptionMap.setMap("客户咨询热线","Customer Consultant","consultant"));
        OPT_MAP_POSITION.put(1606,OptionMap.setMap("客户服务经理","Customer Service Manager","service"));
        OPT_MAP_POSITION.put(1607,OptionMap.setMap("呼叫中心人员","Hot-line Consultant","hotline"));
        OPT_MAP_POSITION.put(1699,OptionMap.setMap("其它","Other","other"));
        OPT_MAP_POSITION.put(1700,OptionMap.setMap("营销/企划/媒介/公关类","Marketing/Public Relations","marketing"));
        OPT_MAP_POSITION.put(1701,OptionMap.setMap("新闻媒介企划","News Media Planning","news"));
        OPT_MAP_POSITION.put(1702,OptionMap.setMap("促销/礼仪专员","Promotion/Comity Clerk","promotion"));
        OPT_MAP_POSITION.put(1703,OptionMap.setMap("公关经理","Public Relations Manager","relationsmana"));
        OPT_MAP_POSITION.put(1704,OptionMap.setMap("公关专员","Public Relations Commissioner","relationscomm"));
        OPT_MAP_POSITION.put(1705,OptionMap.setMap("市场助理/专员","Marketing Assistant/Clerk","marketassis"));
        OPT_MAP_POSITION.put(1706,OptionMap.setMap("市场部主管","Marketing Director","marketdirector"));
        OPT_MAP_POSITION.put(1707,OptionMap.setMap("市场调研/业务分析员","Marketing Research/ Business Analysis","research"));
        OPT_MAP_POSITION.put(1708,OptionMap.setMap("市场/行销企划","Marketing/Sales Planning","saleplan"));
        OPT_MAP_POSITION.put(1709,OptionMap.setMap("市场推广/拓展/合作员","Market Development","marketdev"));
        OPT_MAP_POSITION.put(1710,OptionMap.setMap("产品/品牌企划","Product/Brand Planning","brand"));
        OPT_MAP_POSITION.put(1711,OptionMap.setMap("品牌经理","Brand Manager","brandmana"));
        OPT_MAP_POSITION.put(1712,OptionMap.setMap("价格企划","Price Planning","pricplan"));
        OPT_MAP_POSITION.put(1713,OptionMap.setMap("广告企划/广告制作","Advertisement Planning","advplan"));
        OPT_MAP_POSITION.put(1714,OptionMap.setMap("市场/营销总监","Market Majordomo","majordomo"));
        OPT_MAP_POSITION.put(1715,OptionMap.setMap("市场/营销经理","Marketing Manager","marketMana"));
        OPT_MAP_POSITION.put(1716,OptionMap.setMap("营销师","Marketing Division","division"));
        OPT_MAP_POSITION.put(1717,OptionMap.setMap("客户经理","Customer Manager","cusmanager"));
        OPT_MAP_POSITION.put(1799,OptionMap.setMap("其它","Other","other"));
        OPT_MAP_POSITION.put(1800,OptionMap.setMap("经营管理类","Management",""));
        OPT_MAP_POSITION.put(1801,OptionMap.setMap("{正/副}总裁/总经理/CEO","President, VP, General Manager, CEO",""));
        OPT_MAP_POSITION.put(1802,OptionMap.setMap("专业招商人员","Professional business Staff",""));
        OPT_MAP_POSITION.put(1803,OptionMap.setMap("企业发展规划经理/主管/助理","Corporate Planning Manager",""));
        OPT_MAP_POSITION.put(1804,OptionMap.setMap("首席运营官COO","Chief operation official COO",""));
        OPT_MAP_POSITION.put(1805,OptionMap.setMap("产品经理/主管","Product Manager/Director",""));
        OPT_MAP_POSITION.put(1806,OptionMap.setMap("分公司/办事处经理/主管","Branch Manager/Director",""));
        OPT_MAP_POSITION.put(1807,OptionMap.setMap("部门经理/主管","Department Manager/Department Director",""));
        OPT_MAP_POSITION.put(1808,OptionMap.setMap("总经理助理","President Assistant",""));
        OPT_MAP_POSITION.put(1809,OptionMap.setMap("经理助理","Manager Assistant",""));
        OPT_MAP_POSITION.put(1810,OptionMap.setMap("厂长/副厂长","Factory Director/Vice Factory Director",""));
        OPT_MAP_POSITION.put(1811,OptionMap.setMap("项目经理/主管","Project Manager",""));
        OPT_MAP_POSITION.put(1812,OptionMap.setMap("企划总监","Business Planning Director",""));
        OPT_MAP_POSITION.put(1899,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(1900,OptionMap.setMap("法律/咨询（顾问）类","Law Specialist",""));
        OPT_MAP_POSITION.put(1901,OptionMap.setMap("律师","Lawyer",""));
        OPT_MAP_POSITION.put(1902,OptionMap.setMap("法律顾问","Counselor",""));
        OPT_MAP_POSITION.put(1903,OptionMap.setMap("法务人员","Law clerk",""));
        OPT_MAP_POSITION.put(1904,OptionMap.setMap("律师助理","Lawyer Assistant",""));
        OPT_MAP_POSITION.put(1905,OptionMap.setMap("书记员","Secretary",""));
        OPT_MAP_POSITION.put(1906,OptionMap.setMap("知识产权顾问/专员","Intellectual Property Consultants/Commissioner",""));
        OPT_MAP_POSITION.put(1907,OptionMap.setMap("专利顾问/专员","Patent Consultants/Commissione",""));
        OPT_MAP_POSITION.put(1908,OptionMap.setMap("企业管理顾问","Enterprise management Consultant",""));
        OPT_MAP_POSITION.put(1909,OptionMap.setMap("涉外咨询师","Internationalize Consultant",""));
        OPT_MAP_POSITION.put(1910,OptionMap.setMap("高级猎头顾问","Senior Head-hunter",""));
        OPT_MAP_POSITION.put(1911,OptionMap.setMap("咨询总监/经理","Consultant Manager",""));
        OPT_MAP_POSITION.put(1912,OptionMap.setMap("咨询员/信息中介/专业顾问","Consultation/Information agency/Speciality Consultant",""));
        OPT_MAP_POSITION.put(1913,OptionMap.setMap("企业策划/顾问","Enterprise Planning Consultant",""));
        OPT_MAP_POSITION.put(1999,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(2000,OptionMap.setMap("财务/审（统）计类","Financing/Audit/Stat.",""));
        OPT_MAP_POSITION.put(2001,OptionMap.setMap("税务专员/助理","Tax Clerk",""));
        OPT_MAP_POSITION.put(2002,OptionMap.setMap("出纳员","Treasurer",""));
        OPT_MAP_POSITION.put(2003,OptionMap.setMap("统计员","Statistician",""));
        OPT_MAP_POSITION.put(2004,OptionMap.setMap("注册会计师","Certified Accountant",""));
        OPT_MAP_POSITION.put(2005,OptionMap.setMap("会计/会计助理","Accountant Assistant",""));
        OPT_MAP_POSITION.put(2006,OptionMap.setMap("账目（进出口）管理","Account Management",""));
        OPT_MAP_POSITION.put(2007,OptionMap.setMap("成本经理/主管","Cost Manager/Supervisor",""));
        OPT_MAP_POSITION.put(2008,OptionMap.setMap("成本分析/核算员","Cost Analysis/Adjust",""));
        OPT_MAP_POSITION.put(2009,OptionMap.setMap("成本管理员","Cost Accounting Specialist",""));
        OPT_MAP_POSITION.put(2010,OptionMap.setMap("注册税务师","Certified Tax Agents",""));
        OPT_MAP_POSITION.put(2011,OptionMap.setMap("税务经理/主管","Tax Manager/Supervisor",""));
        OPT_MAP_POSITION.put(2012,OptionMap.setMap("审计经理/主管","Audit Manager/Supervisor",""));
        OPT_MAP_POSITION.put(2013,OptionMap.setMap("审计专员/助理","Audit Executive/Assistant",""));
        OPT_MAP_POSITION.put(2014,OptionMap.setMap("注册审计师","Certified Auditor",""));
        OPT_MAP_POSITION.put(2015,OptionMap.setMap("财务主管/经理","Finance Director/Manager",""));
        OPT_MAP_POSITION.put(2016,OptionMap.setMap("财务顾问/助理","Finance Consultant",""));
        OPT_MAP_POSITION.put(2017,OptionMap.setMap("财务分析师","Finance Analysis",""));
        OPT_MAP_POSITION.put(2018,OptionMap.setMap("首席财务官CFO/财务总监","Chief Financial Officer CFO",""));
        OPT_MAP_POSITION.put(2019,OptionMap.setMap("财务管理师","Financial Control Teacher",""));
        OPT_MAP_POSITION.put(2099,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(2100,OptionMap.setMap("金融/保险/银行类","Finance/Securities/investment",""));
        OPT_MAP_POSITION.put(2101,OptionMap.setMap("评估/分析师","Evaluating",""));
        OPT_MAP_POSITION.put(2102,OptionMap.setMap("精算师","Actuaries",""));
        OPT_MAP_POSITION.put(2103,OptionMap.setMap("稽核员","Investigation",""));
        OPT_MAP_POSITION.put(2104,OptionMap.setMap("拍卖师","Auctions",""));
        OPT_MAP_POSITION.put(2105,OptionMap.setMap("证券经纪人","Securities Broke",""));
        OPT_MAP_POSITION.put(2106,OptionMap.setMap("证券期货从业人员","Securities/Futures",""));
        OPT_MAP_POSITION.put(2107,OptionMap.setMap("证券分析师","Securities Analysts",""));
        OPT_MAP_POSITION.put(2108,OptionMap.setMap("黄金投资分析师","Gold investment Analyst",""));
        OPT_MAP_POSITION.put(2109,OptionMap.setMap("注册金融分析师","Registration finance Analyst",""));
        OPT_MAP_POSITION.put(2110,OptionMap.setMap("金融投资分析员","Finance investing Analysis",""));
        OPT_MAP_POSITION.put(2111,OptionMap.setMap("金融/经济研究员","Finance investing Analysis",""));
        OPT_MAP_POSITION.put(2112,OptionMap.setMap("炒股操盘手","Stock Manipulator",""));
        OPT_MAP_POSITION.put(2113,OptionMap.setMap("投资/基金项目经理","Investment Manager",""));
        OPT_MAP_POSITION.put(2114,OptionMap.setMap("融资经理/主管","Financing Manager/Directory",""));
        OPT_MAP_POSITION.put(2115,OptionMap.setMap("融资专员/助理","Financing Commissioner/Assistant",""));
        OPT_MAP_POSITION.put(2116,OptionMap.setMap("注册分析师","Certified Investment/Financial Analyst",""));
        OPT_MAP_POSITION.put(2117,OptionMap.setMap("保险业务经理/主管","Business Manager/Supervisor",""));
        OPT_MAP_POSITION.put(2118,OptionMap.setMap("保险经纪人/代理人","Insurance Broker/Agent",""));
        OPT_MAP_POSITION.put(2119,OptionMap.setMap("保险产品开发/项目策划师","Product Development/Planner",""));
        OPT_MAP_POSITION.put(2120,OptionMap.setMap("保险客户服务/续期管理","Customer Service",""));
        OPT_MAP_POSITION.put(2121,OptionMap.setMap("理财顾问/财务规划师","Financial Advisor/Financial Planner",""));
        OPT_MAP_POSITION.put(2122,OptionMap.setMap("保险理赔专员","Claim Management",""));
        OPT_MAP_POSITION.put(2123,OptionMap.setMap("保险培训师","Trainer",""));
        OPT_MAP_POSITION.put(2124,OptionMap.setMap("外汇交易专员","Foreign Exchange Commissioner",""));
        OPT_MAP_POSITION.put(2125,OptionMap.setMap("出纳员/银行专员","Treasurer/Bank Clerk",""));
        OPT_MAP_POSITION.put(2126,OptionMap.setMap("预结算专员","Budgeting/Balance Clerk",""));
        OPT_MAP_POSITION.put(2127,OptionMap.setMap("大堂经理","Hall Manager",""));
        OPT_MAP_POSITION.put(2128,OptionMap.setMap("银行卡/电子银行业务推广员","Credit Card/E-banking business Develop",""));
        OPT_MAP_POSITION.put(2129,OptionMap.setMap("信贷管理/信用调查/分析人员","Loan/Credit Officer",""));
        OPT_MAP_POSITION.put(2130,OptionMap.setMap("银行行长/副行长","Bank/Vice-President",""));
        OPT_MAP_POSITION.put(2131,OptionMap.setMap("银行信贷专员","Commissioner bank Credit",""));
        OPT_MAP_POSITION.put(2199,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(2200,OptionMap.setMap("人力资源/行政类","Administration/Human Resource",""));
        OPT_MAP_POSITION.put(2201,OptionMap.setMap("培训经理/主管/专员","Training Manager/Director",""));
        OPT_MAP_POSITION.put(2202,OptionMap.setMap("薪资福利经理/主管/专员","Compensation Manager/Director/Clerk",""));
        OPT_MAP_POSITION.put(2203,OptionMap.setMap("人力资源总监","Human Resource Majordomo",""));
        OPT_MAP_POSITION.put(2204,OptionMap.setMap("人事经理/主管/专员","Human Resource Manager",""));
        OPT_MAP_POSITION.put(2205,OptionMap.setMap("人事助理/文员","Human Resource Assistant",""));
        OPT_MAP_POSITION.put(2206,OptionMap.setMap("绩效考核经理/主管/专员","Performance Manager/Director/Clerk",""));
        OPT_MAP_POSITION.put(2207,OptionMap.setMap("招聘经理/主管/专员","Recruitment Manger/Director/Clerk",""));
        OPT_MAP_POSITION.put(2208,OptionMap.setMap("行政总监","Human Resource Majordomo",""));
        OPT_MAP_POSITION.put(2209,OptionMap.setMap("行政经理/主管","Administration Manager",""));
        OPT_MAP_POSITION.put(2210,OptionMap.setMap("行政助理/文员","Administration Assistant/Civilian",""));
        OPT_MAP_POSITION.put(2211,OptionMap.setMap("员工关系管理","Staff Relationship Supervisor",""));
        OPT_MAP_POSITION.put(2212,OptionMap.setMap("企业文化主管/专员","Enterprise Culture Specialist",""));
        OPT_MAP_POSITION.put(2213,OptionMap.setMap("办公室主任","Office Manager",""));
        OPT_MAP_POSITION.put(2214,OptionMap.setMap("总务","General Affairs",""));
        OPT_MAP_POSITION.put(2215,OptionMap.setMap("合同管理专员","Contract management special Commissioner",""));
        OPT_MAP_POSITION.put(2299,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(2300,OptionMap.setMap("文职类","Civilian Posts",""));
        OPT_MAP_POSITION.put(2301,OptionMap.setMap("文案策划/资料编写","Article Planning/Materials Writing",""));
        OPT_MAP_POSITION.put(2302,OptionMap.setMap("秘书/高级秘书","Secretary /Senior Secretary",""));
        OPT_MAP_POSITION.put(2303,OptionMap.setMap("话务员","Telephonist",""));
        OPT_MAP_POSITION.put(2304,OptionMap.setMap("前台文员","Reception",""));
        OPT_MAP_POSITION.put(2305,OptionMap.setMap("文员/高级文员","Civilian /Senior Civilian",""));
        OPT_MAP_POSITION.put(2306,OptionMap.setMap("电脑操作员/打字员","Computer Operator/Type Writer",""));
        OPT_MAP_POSITION.put(2307,OptionMap.setMap("图书情报/档案管理","Books Information/Files Administration",""));
        OPT_MAP_POSITION.put(2399,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(2400,OptionMap.setMap("工业/工厂类","Industry/Factories",""));
        OPT_MAP_POSITION.put(2401,OptionMap.setMap("资材主管/资材助理","Materials and Equipment Manager/ Assistant",""));
        OPT_MAP_POSITION.put(2402,OptionMap.setMap("仓库管理员","Storage Controller",""));
        OPT_MAP_POSITION.put(2403,OptionMap.setMap("计划员/调度员","Dispatcher",""));
        OPT_MAP_POSITION.put(2404,OptionMap.setMap("跟单员","Order Clerk",""));
        OPT_MAP_POSITION.put(2405,OptionMap.setMap("PMC/SMT技术员","SMT Technician",""));
        OPT_MAP_POSITION.put(2406,OptionMap.setMap("工艺工程师","Technic Engineer",""));
        OPT_MAP_POSITION.put(2407,OptionMap.setMap("生管主管/督导","Production Management Director",""));
        OPT_MAP_POSITION.put(2408,OptionMap.setMap("生管员","Production Management Clerk",""));
        OPT_MAP_POSITION.put(2409,OptionMap.setMap("PE工程师","PE Engineer",""));
        OPT_MAP_POSITION.put(2410,OptionMap.setMap("IE工程师","IE Engineer",""));
        OPT_MAP_POSITION.put(2411,OptionMap.setMap("ME工程师","ME Engineer",""));
        OPT_MAP_POSITION.put(2412,OptionMap.setMap("工程设备工程师","Engineering Device Engineer",""));
        OPT_MAP_POSITION.put(2413,OptionMap.setMap("组长/拉长","Team leader",""));
        OPT_MAP_POSITION.put(2414,OptionMap.setMap("物控员","Material Commissioner",""));
        OPT_MAP_POSITION.put(2415,OptionMap.setMap("统计员","Statistician",""));
        OPT_MAP_POSITION.put(2416,OptionMap.setMap("制造课长","ME Engineer",""));
        OPT_MAP_POSITION.put(2417,OptionMap.setMap("R&D经理","RD Manager",""));
        OPT_MAP_POSITION.put(2418,OptionMap.setMap("储备干部","Stockpiles the Cadre",""));
        OPT_MAP_POSITION.put(2419,OptionMap.setMap("车间经理/主管","Workshop manager/Director",""));
        OPT_MAP_POSITION.put(2420,OptionMap.setMap("维修工程师","Services Engineer",""));
        OPT_MAP_POSITION.put(2421,OptionMap.setMap("新产品导入工程师","The new product inducts Engineer",""));
        OPT_MAP_POSITION.put(2422,OptionMap.setMap("物控经理/主管","Material Manager/Director",""));
        OPT_MAP_POSITION.put(2423,OptionMap.setMap("设备经理/主管","Device Manager/Director",""));
        OPT_MAP_POSITION.put(2424,OptionMap.setMap("生产经理/主管","Product Manager",""));
        OPT_MAP_POSITION.put(2425,OptionMap.setMap("工程经理/主管","Engineering Manager/Director",""));
        OPT_MAP_POSITION.put(2426,OptionMap.setMap("产品开发","Product Development",""));
        OPT_MAP_POSITION.put(2427,OptionMap.setMap("采购管理","Procurement Management",""));
        OPT_MAP_POSITION.put(2499,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(2500,OptionMap.setMap("质量/安全/环境管理类","Quality/Safety Management",""));
        OPT_MAP_POSITION.put(2501,OptionMap.setMap("质量管理/测试","Quality/Safety",""));
        OPT_MAP_POSITION.put(2502,OptionMap.setMap("经理/主管（QA/QC经理）","QA/QC Manager/Supervisor",""));
        OPT_MAP_POSITION.put(2503,OptionMap.setMap("质量管理/测试工程师（QA/QC工程师）","QA/QC Engineer",""));
        OPT_MAP_POSITION.put(2504,OptionMap.setMap("质量管理/验货员（QA/QC）","Quality Management QA/QC",""));
        OPT_MAP_POSITION.put(2505,OptionMap.setMap("ISO9000质量检验员/测试员","Quality Inspector/Tester",""));
        OPT_MAP_POSITION.put(2506,OptionMap.setMap("化验/检验员","Assay/Test Clerk",""));
        OPT_MAP_POSITION.put(2507,OptionMap.setMap("品管员","PQA Commissioner",""));
        OPT_MAP_POSITION.put(2508,OptionMap.setMap("品质工程师","PQA Engineer",""));
        OPT_MAP_POSITION.put(2509,OptionMap.setMap("食品检验工","Food Inspection",""));
        OPT_MAP_POSITION.put(2510,OptionMap.setMap("故障分析工程师","Failure Analysis Engineer",""));
        OPT_MAP_POSITION.put(2511,OptionMap.setMap("采购材料、设备质量管理","Supplies & Equipment Quality Management",""));
        OPT_MAP_POSITION.put(2512,OptionMap.setMap("认证工程师/审核员","Certification Engineer/Auditor",""));
        OPT_MAP_POSITION.put(2513,OptionMap.setMap("体系工程师/审核员","Systems Engineer/Auditor",""));
        OPT_MAP_POSITION.put(2514,OptionMap.setMap("安全/健康/环境经理/主管","Safety/Health/Environmental Manager/Supervisor",""));
        OPT_MAP_POSITION.put(2515,OptionMap.setMap("安全/健康/环境工程师","Safety/Health/Environmental Engineer",""));
        OPT_MAP_POSITION.put(2516,OptionMap.setMap("安全主任","Security Director",""));
        OPT_MAP_POSITION.put(2517,OptionMap.setMap("供应商管理","Supplier/Vendor Management",""));
        OPT_MAP_POSITION.put(2518,OptionMap.setMap("供应商质量工程师","Supplier quality Engineer",""));
        OPT_MAP_POSITION.put(2599,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(2600,OptionMap.setMap("机械（电）/仪表类","Mechanism/Instrument",""));
        OPT_MAP_POSITION.put(2601,OptionMap.setMap("机械制图员","Mechanical cartography",""));
        OPT_MAP_POSITION.put(2602,OptionMap.setMap("结构设计师","Structure Engineer",""));
        OPT_MAP_POSITION.put(2603,OptionMap.setMap("飞行器设计工程师","Flight vehicle project Engineer",""));
        OPT_MAP_POSITION.put(2604,OptionMap.setMap("机械工艺师","Machine Engineer",""));
        OPT_MAP_POSITION.put(2605,OptionMap.setMap("机械设计/制造工程师","Machine Design and Manufacture Engineer",""));
        OPT_MAP_POSITION.put(2606,OptionMap.setMap("机械工程师","Machine Engineer",""));
        OPT_MAP_POSITION.put(2607,OptionMap.setMap("船舶机械工程师","Watercraft machine Engineer",""));
        OPT_MAP_POSITION.put(2608,OptionMap.setMap("CNC工程师","CNC Engineer",""));
        OPT_MAP_POSITION.put(2609,OptionMap.setMap("食品机械工程师","Grocery machine Engineer",""));
        OPT_MAP_POSITION.put(2610,OptionMap.setMap("焊接机械工程师","Jointing machine Engineer",""));
        OPT_MAP_POSITION.put(2611,OptionMap.setMap("精密机械/仪器仪表工程师","Precision optical machinery/Instrument and meter Engineer",""));
        OPT_MAP_POSITION.put(2612,OptionMap.setMap("纺织机械工程师","Spin machine Engineer",""));
        OPT_MAP_POSITION.put(2613,OptionMap.setMap("汽车/摩托车工程师","Automobile/Autocycle Engineer",""));
        OPT_MAP_POSITION.put(2614,OptionMap.setMap("表面处理工程师","Surface treatment Engineer",""));
        OPT_MAP_POSITION.put(2615,OptionMap.setMap("气动/液压","Hydraulic Pressure/Gas driven",""));
        OPT_MAP_POSITION.put(2616,OptionMap.setMap("机电一体化","Integration of machinery",""));
        OPT_MAP_POSITION.put(2617,OptionMap.setMap("铸造/锻造工程师","Foundry/Smithing Engineer",""));
        OPT_MAP_POSITION.put(2618,OptionMap.setMap("数控技术员","Numerical control Technician",""));
        OPT_MAP_POSITION.put(2619,OptionMap.setMap("锅炉/压力容器","Boiler/Pressure vessel",""));
        OPT_MAP_POSITION.put(2620,OptionMap.setMap("设备修理","Device Repairment",""));
        OPT_MAP_POSITION.put(2621,OptionMap.setMap("电镀/热处理","Galvanization/Heat Treatment",""));
        OPT_MAP_POSITION.put(2622,OptionMap.setMap("五金矿产/金属制品","Ironware, mineral resources/metalwork",""));
        OPT_MAP_POSITION.put(2699,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(2700,OptionMap.setMap("模具类","Mold",""));
        OPT_MAP_POSITION.put(2701,OptionMap.setMap("模具工程师","Matrix Engineer",""));
        OPT_MAP_POSITION.put(2702,OptionMap.setMap("塑胶模师傅/普师/补师","Plastics Mold Worker",""));
        OPT_MAP_POSITION.put(2703,OptionMap.setMap("五金模师傅/普师/补师","Hardware Mold Worker",""));
        OPT_MAP_POSITION.put(2704,OptionMap.setMap("塑胶模经理/主管","Plastics Mold Manager/Supervisor",""));
        OPT_MAP_POSITION.put(2705,OptionMap.setMap("五金模经理/主管","Hardware Mold Manager/Supervisor",""));
        OPT_MAP_POSITION.put(2706,OptionMap.setMap("模具QC/品管/品保","Mould QC",""));
        OPT_MAP_POSITION.put(2707,OptionMap.setMap("注塑成型工程师","Prototyping Engineer",""));
        OPT_MAP_POSITION.put(2708,OptionMap.setMap("冲压工程师","Ramming Engineer",""));
        OPT_MAP_POSITION.put(2709,OptionMap.setMap("跟模/试模/校模","Mold Worker/Mold Tester/Mold Calibrater",""));
        OPT_MAP_POSITION.put(2710,OptionMap.setMap("省模/组模/修模","Mold Assembler/Mold Repairer",""));
        OPT_MAP_POSITION.put(2711,OptionMap.setMap("CNC/编程","CNC/ Programme",""));
        OPT_MAP_POSITION.put(2712,OptionMap.setMap("走丝/慢走丝/线切割","Drawbench Technician/Line cutting Technician",""));
        OPT_MAP_POSITION.put(2713,OptionMap.setMap("铣床/磨床/钻床","Miller/Grinder/Driller",""));
        OPT_MAP_POSITION.put(2714,OptionMap.setMap("冲床/车床/火花机","Puncher/Latheman/Spark Machine Operator",""));
        OPT_MAP_POSITION.put(2715,OptionMap.setMap("模具/手版制作","Mold Production",""));
        OPT_MAP_POSITION.put(2716,OptionMap.setMap("刀具/夹具","Reamer Engineer/Jig Engineer",""));
        OPT_MAP_POSITION.put(2799,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(2800,OptionMap.setMap("房地产/物业类","Realty Development",""));
        OPT_MAP_POSITION.put(2801,OptionMap.setMap("房地产中介","Realty agency",""));
        OPT_MAP_POSITION.put(2802,OptionMap.setMap("房地产销售","Real Estate Sales",""));
        OPT_MAP_POSITION.put(2803,OptionMap.setMap("商业地产策划师","Commercial Real Estate Strategist",""));
        OPT_MAP_POSITION.put(2804,OptionMap.setMap("物业管理","Infrastructure management",""));
        OPT_MAP_POSITION.put(2805,OptionMap.setMap("物业招商/租赁/租售员","Property Lease/Rent",""));
        OPT_MAP_POSITION.put(2806,OptionMap.setMap("房地产开发/策划经理","Realty Development/Planning Manager",""));
        OPT_MAP_POSITION.put(2807,OptionMap.setMap("房地产开发/策划专员","Realty Development/Planning Commissioner",""));
        OPT_MAP_POSITION.put(2808,OptionMap.setMap("房地产评估师","Realty evaluation",""));
        OPT_MAP_POSITION.put(2809,OptionMap.setMap("房产测量员","Property Surveyors",""));
        OPT_MAP_POSITION.put(2899,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(2900,OptionMap.setMap("建筑/施工/园林（园艺）类","Realty/Architecture/Construction",""));
        OPT_MAP_POSITION.put(2901,OptionMap.setMap("投标主管","Bids the manager",""));
        OPT_MAP_POSITION.put(2902,OptionMap.setMap("报批/报建专员","Approval/reported to the Commissioner",""));
        OPT_MAP_POSITION.put(2903,OptionMap.setMap("建筑（结构）设计工程师","Architecture engineer",""));
        OPT_MAP_POSITION.put(2904,OptionMap.setMap("建筑制图工程师","Architecture cartography",""));
        OPT_MAP_POSITION.put(2905,OptionMap.setMap("注册建筑师","Registered architect",""));
        OPT_MAP_POSITION.put(2906,OptionMap.setMap("土建工程师","Construction Engineer",""));
        OPT_MAP_POSITION.put(2907,OptionMap.setMap("工民建","Industry/Civilian Architecture",""));
        OPT_MAP_POSITION.put(2908,OptionMap.setMap("建筑工程验收师","Construction Project Inspector",""));
        OPT_MAP_POSITION.put(2909,OptionMap.setMap("绘图员","Plotter",""));
        OPT_MAP_POSITION.put(2910,OptionMap.setMap("建筑工程造价/预结算师","Construction Cost/pre-clearing Division",""));
        OPT_MAP_POSITION.put(2911,OptionMap.setMap("施工员","Construction",""));
        OPT_MAP_POSITION.put(2912,OptionMap.setMap("路桥技术/隧道工程","Route and Bridge tech./Tunnel engineering",""));
        OPT_MAP_POSITION.put(2913,OptionMap.setMap("基建/岩土工程","Capital construction",""));
        OPT_MAP_POSITION.put(2914,OptionMap.setMap("工程监理","Engineering superintendent",""));
        OPT_MAP_POSITION.put(2915,OptionMap.setMap("工程项目经理","Engineering Project Manager",""));
        OPT_MAP_POSITION.put(2916,OptionMap.setMap("管道（水、电）","Pipeline/Refrigeration",""));
        OPT_MAP_POSITION.put(2917,OptionMap.setMap("给排水/供水（电）工程师","Drainage/water(electric) supply Engineer",""));
        OPT_MAP_POSITION.put(2918,OptionMap.setMap("制冷暖通","Refrigeration/Central heating",""));
        OPT_MAP_POSITION.put(2919,OptionMap.setMap("港口与航道工程","Port and sea-route engineering",""));
        OPT_MAP_POSITION.put(2920,OptionMap.setMap("资料员","File Clerk",""));
        OPT_MAP_POSITION.put(2921,OptionMap.setMap("园艺/园林技术员","Gardening/botanical garden Technician",""));
        OPT_MAP_POSITION.put(2922,OptionMap.setMap("园艺/园林设计","Gardenning Designer",""));
        OPT_MAP_POSITION.put(2923,OptionMap.setMap("景观设计师","Landscape Designer",""));
        OPT_MAP_POSITION.put(2924,OptionMap.setMap("插花员","Flower arrangement",""));
        OPT_MAP_POSITION.put(2925,OptionMap.setMap("城市规划与设计","Urban Design/Planning",""));
        OPT_MAP_POSITION.put(2926,OptionMap.setMap("园林监理","Botanical garden overseeing",""));
        OPT_MAP_POSITION.put(2927,OptionMap.setMap("园艺/园林工程师","Gardening/botanical garden Engineer",""));
        OPT_MAP_POSITION.put(2928,OptionMap.setMap("建筑施工管理","Construction Management",""));
        OPT_MAP_POSITION.put(2999,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(3000,OptionMap.setMap("设计类","advertising(upholster) Design",""));
        OPT_MAP_POSITION.put(3001,OptionMap.setMap("广告创意总监","Advertisement creativity Inspector General",""));
        OPT_MAP_POSITION.put(3002,OptionMap.setMap("广告设计/创意策划师","Advertisement design/Originality Planning",""));
        OPT_MAP_POSITION.put(3003,OptionMap.setMap("文案/媒体策划","Planning",""));
        OPT_MAP_POSITION.put(3004,OptionMap.setMap("室内（外）装修/装潢设计","Interior/Exterior Designer/Decorator",""));
        OPT_MAP_POSITION.put(3005,OptionMap.setMap("商业美术设计师","Commercial fine arts Designer",""));
        OPT_MAP_POSITION.put(3006,OptionMap.setMap("陈列/展览设计","Exhibition/display Design",""));
        OPT_MAP_POSITION.put(3007,OptionMap.setMap("三维动画设计","3D Movie Design",""));
        OPT_MAP_POSITION.put(3008,OptionMap.setMap("多媒体设计制作员","Multimedia Design",""));
        OPT_MAP_POSITION.put(3009,OptionMap.setMap("动漫设计制作员","CARTOON design Producers",""));
        OPT_MAP_POSITION.put(3010,OptionMap.setMap("产品包装设计","Product casing Design",""));
        OPT_MAP_POSITION.put(3011,OptionMap.setMap("工艺品设计","Craftwork Design",""));
        OPT_MAP_POSITION.put(3012,OptionMap.setMap("工业产品设计","Industry product Design",""));
        OPT_MAP_POSITION.put(3013,OptionMap.setMap("雕塑设计","Sculpture Design",""));
        OPT_MAP_POSITION.put(3014,OptionMap.setMap("纺织/服饰（装）设计","Spin/finery Design",""));
        OPT_MAP_POSITION.put(3015,OptionMap.setMap("灯光设计","Light Design",""));
        OPT_MAP_POSITION.put(3016,OptionMap.setMap("家具设计","Furniture Design",""));
        OPT_MAP_POSITION.put(3017,OptionMap.setMap("形象设计/平面设计","Visualize Design/Plane Design",""));
        OPT_MAP_POSITION.put(3018,OptionMap.setMap("玩具设计","Toy Design",""));
        OPT_MAP_POSITION.put(3019,OptionMap.setMap("珠宝设计/首饰设计","Jewellery Design/Jewelry Design",""));
        OPT_MAP_POSITION.put(3020,OptionMap.setMap("绘图员","Plotter",""));
        OPT_MAP_POSITION.put(3021,OptionMap.setMap("游戏设计","Game Design",""));
        OPT_MAP_POSITION.put(3022,OptionMap.setMap("模具设计","Mold design",""));
        OPT_MAP_POSITION.put(3099,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(3100,OptionMap.setMap("影视/广播/媒体/摄影类","Movie/Photopgraphy",""));
        OPT_MAP_POSITION.put(3101,OptionMap.setMap("影视策划/制作人员","Movie planning/Producer",""));
        OPT_MAP_POSITION.put(3102,OptionMap.setMap("影音器材管理/道具员","Media device administrator",""));
        OPT_MAP_POSITION.put(3103,OptionMap.setMap("化妆/造型师","Makeup Artist/Image Designer",""));
        OPT_MAP_POSITION.put(3104,OptionMap.setMap("布景师","Art Director",""));
        OPT_MAP_POSITION.put(3105,OptionMap.setMap("模特儿","Model",""));
        OPT_MAP_POSITION.put(3106,OptionMap.setMap("摄影师/摄影助理","Photographer/Assistant Cameraman",""));
        OPT_MAP_POSITION.put(3107,OptionMap.setMap("灯光师/剪辑师/冲印师/音效师","Lighting Engineer/Film Cutter/Photo Division/Sound effects Director",""));
        OPT_MAP_POSITION.put(3108,OptionMap.setMap("节目主持人","M.C",""));
        OPT_MAP_POSITION.put(3109,OptionMap.setMap("播音员","Announcer",""));
        OPT_MAP_POSITION.put(3110,OptionMap.setMap("配音员","Recording Director",""));
        OPT_MAP_POSITION.put(3111,OptionMap.setMap("记者","Reporter",""));
        OPT_MAP_POSITION.put(3112,OptionMap.setMap("演员","Actor/actress",""));
        OPT_MAP_POSITION.put(3113,OptionMap.setMap("导演/副导演/助理导演","Director/Assistant Director",""));
        OPT_MAP_POSITION.put(3114,OptionMap.setMap("经纪人/星探","Manager/Talent",""));
        OPT_MAP_POSITION.put(3199,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(3200,OptionMap.setMap("文体教育/培训类","Culture/Education",""));
        OPT_MAP_POSITION.put(3201,OptionMap.setMap("文化艺术","Culture/Arts",""));
        OPT_MAP_POSITION.put(3202,OptionMap.setMap("教授","Professor",""));
        OPT_MAP_POSITION.put(3203,OptionMap.setMap("讲师","Lecturer",""));
        OPT_MAP_POSITION.put(3204,OptionMap.setMap("助教","Assistant",""));
        OPT_MAP_POSITION.put(3205,OptionMap.setMap("高等教育","Higher education",""));
        OPT_MAP_POSITION.put(3206,OptionMap.setMap("中级教育","Intermediate education",""));
        OPT_MAP_POSITION.put(3207,OptionMap.setMap("初级教育","Primary education",""));
        OPT_MAP_POSITION.put(3208,OptionMap.setMap("小学/幼儿教育","Grade school/infant education",""));
        OPT_MAP_POSITION.put(3209,OptionMap.setMap("竞技/体育","Sports",""));
        OPT_MAP_POSITION.put(3210,OptionMap.setMap("家教","Family education",""));
        OPT_MAP_POSITION.put(3211,OptionMap.setMap("培训经理/主管","Training Managers/Directors",""));
        OPT_MAP_POSITION.put(3212,OptionMap.setMap("职业教育/培训","Vocational education/Training",""));
        OPT_MAP_POSITION.put(3213,OptionMap.setMap("计算机培训师","Computer Training",""));
        OPT_MAP_POSITION.put(3214,OptionMap.setMap("英语培训师","English Training",""));
        OPT_MAP_POSITION.put(3215,OptionMap.setMap("培训专员","Trains special Commissioner",""));
        OPT_MAP_POSITION.put(3216,OptionMap.setMap("驾校教练","Driving Master",""));
        OPT_MAP_POSITION.put(3217,OptionMap.setMap("教务/教学管理人员","Educational Administration/Teaching Management Staff",""));
        OPT_MAP_POSITION.put(3218,OptionMap.setMap("外籍教师","Foreign teacher",""));
        OPT_MAP_POSITION.put(3219,OptionMap.setMap("教材编辑","Sports/Gym Teacher",""));
        OPT_MAP_POSITION.put(3299,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(3300,OptionMap.setMap("卫生医疗/保健护理（美容）类","Sanitation/Treatment/Healthing",""));
        OPT_MAP_POSITION.put(3301,OptionMap.setMap("医生/医师/理疗师","Doctor/Physician/Physical Therapist",""));
        OPT_MAP_POSITION.put(3302,OptionMap.setMap("牙科/心理/外科/内科/预防/妇产科医生","Dentist/Psychology doctor/Surgeon/Internist/Prevent doctor/Accoucheur",""));
        OPT_MAP_POSITION.put(3303,OptionMap.setMap("护士/护理员","Nurse",""));
        OPT_MAP_POSITION.put(3304,OptionMap.setMap("针灸推拿/妇幼保健/卫生防疫","Acupuncture/message/Women/children heathcare/Sanitation/epidemic prevention",""));
        OPT_MAP_POSITION.put(3305,OptionMap.setMap("临床医学/研究员/协调员","Clinic iatrology",""));
        OPT_MAP_POSITION.put(3306,OptionMap.setMap("药剂/中药/西药/药检师","Medicament/Chinese traditional/Western medicine",""));
        OPT_MAP_POSITION.put(3307,OptionMap.setMap("药库主任/药剂师","Pharmacist",""));
        OPT_MAP_POSITION.put(3308,OptionMap.setMap("兽医","Farrier",""));
        OPT_MAP_POSITION.put(3309,OptionMap.setMap("美容/化妆顾问/美容助理","Beauty/cosmetics Consultant",""));
        OPT_MAP_POSITION.put(3310,OptionMap.setMap("发型设计师","Hairstyle Designer",""));
        OPT_MAP_POSITION.put(3311,OptionMap.setMap("营养师/美甲师","Dietitian/Nail Specialist",""));
        OPT_MAP_POSITION.put(3312,OptionMap.setMap("保健/健美师","Heathcare/ Gymnasium",""));
        OPT_MAP_POSITION.put(3313,OptionMap.setMap("健身教练/顾问","Fitness Trainer/Consultant",""));
        OPT_MAP_POSITION.put(3314,OptionMap.setMap("瑜伽/舞蹈老师/瘦身顾问","Yoga/Dance Instructor",""));
        OPT_MAP_POSITION.put(3315,OptionMap.setMap("按摩/足疗","Spa/Massage/Foot Care",""));
        OPT_MAP_POSITION.put(3316,OptionMap.setMap("宠物护理/美容","Pet care",""));
        OPT_MAP_POSITION.put(3317,OptionMap.setMap("麻醉师","Anesthetist",""));
        OPT_MAP_POSITION.put(3399,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(3400,OptionMap.setMap("化工/制药/医疗器械类","Chemical/Pharmacy",""));
        OPT_MAP_POSITION.put(3401,OptionMap.setMap("化工技术应用","Chemical Technical Application",""));
        OPT_MAP_POSITION.put(3402,OptionMap.setMap("表面处理","Surface Treatment",""));
        OPT_MAP_POSITION.put(3403,OptionMap.setMap("日用化工","Daily-use chemical industry",""));
        OPT_MAP_POSITION.put(3404,OptionMap.setMap("化工器械销售","Instrument sale",""));
        OPT_MAP_POSITION.put(3405,OptionMap.setMap("生物化工","Biochemical industry",""));
        OPT_MAP_POSITION.put(3406,OptionMap.setMap("造纸/废品处理","Paper making/waster disposal",""));
        OPT_MAP_POSITION.put(3407,OptionMap.setMap("环保技术","Environmental Technology",""));
        OPT_MAP_POSITION.put(3408,OptionMap.setMap("玻璃/硅酸盐工业","Glass/Silicate industry",""));
        OPT_MAP_POSITION.put(3409,OptionMap.setMap("农药、化肥","Pesticide/Chemical fertilizer",""));
        OPT_MAP_POSITION.put(3410,OptionMap.setMap("无机化工/有机化工","Abio-chemical/Organic chemical",""));
        OPT_MAP_POSITION.put(3411,OptionMap.setMap("高分子化工/化纤/新材料","Macromolecule chemical/Chemical fibre/New materials",""));
        OPT_MAP_POSITION.put(3412,OptionMap.setMap("精细化工/分析化工/电镀化工","Fine chemical/Analyse chemical/Plating chemical",""));
        OPT_MAP_POSITION.put(3413,OptionMap.setMap("化学药剂/药品","Chemistry medicament",""));
        OPT_MAP_POSITION.put(3414,OptionMap.setMap("生物制药","Biology pharmacy",""));
        OPT_MAP_POSITION.put(3415,OptionMap.setMap("药品注册师","Pharmaceuticals Register Specialist",""));
        OPT_MAP_POSITION.put(3416,OptionMap.setMap("药品生产/质量管理员","Pharmaceutical Manufacturing/Quality Management",""));
        OPT_MAP_POSITION.put(3417,OptionMap.setMap("医药技术研发管理人员","Pharmaceutical Technology R&D Management",""));
        OPT_MAP_POSITION.put(3418,OptionMap.setMap("医药销售经理/主管","Pharmaceutical Sales Manager",""));
        OPT_MAP_POSITION.put(3419,OptionMap.setMap("医疗器械市场推广/销售","Medical Equipment Sales",""));
        OPT_MAP_POSITION.put(3420,OptionMap.setMap("医药代表","Curative agent",""));
        OPT_MAP_POSITION.put(3421,OptionMap.setMap("医药检验","Medicine checker",""));
        OPT_MAP_POSITION.put(3499,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(3500,OptionMap.setMap("能源动力类","Energy sources/Power",""));
        OPT_MAP_POSITION.put(3501,OptionMap.setMap("水利/水电","Irrigation works/water and electricity",""));
        OPT_MAP_POSITION.put(3502,OptionMap.setMap("核电/火电","nuclear-powered/fire-powered electricity",""));
        OPT_MAP_POSITION.put(3503,OptionMap.setMap("电厂/电力","Power plant",""));
        OPT_MAP_POSITION.put(3504,OptionMap.setMap("制冷/暖通","Refrigeration/Heating",""));
        OPT_MAP_POSITION.put(3505,OptionMap.setMap("空调/锅炉","Air-conditioning/boiler",""));
        OPT_MAP_POSITION.put(3506,OptionMap.setMap("石油/天燃气/储运","Petroleum/natural gas",""));
        OPT_MAP_POSITION.put(3507,OptionMap.setMap("太阳能","Solar",""));
        OPT_MAP_POSITION.put(3508,OptionMap.setMap("城市燃气","City gas",""));
        OPT_MAP_POSITION.put(3509,OptionMap.setMap("光伏","PV",""));
        OPT_MAP_POSITION.put(3599,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(3600,OptionMap.setMap("酒店宾馆/餐饮旅游类","Hotel/Restaurant/Junketing",""));
        OPT_MAP_POSITION.put(3601,OptionMap.setMap("酒店/宾馆经理","Hotel/guesthouse Manager",""));
        OPT_MAP_POSITION.put(3602,OptionMap.setMap("大堂经理/副理","Lobby manager",""));
        OPT_MAP_POSITION.put(3603,OptionMap.setMap("楼面/餐厅/客房部长","Floor manager/director",""));
        OPT_MAP_POSITION.put(3604,OptionMap.setMap("酒店管理","Hotel manager",""));
        OPT_MAP_POSITION.put(3605,OptionMap.setMap("订票/订房服务员","Reservations/booking Service",""));
        OPT_MAP_POSITION.put(3606,OptionMap.setMap("咨客/前台接待/礼仪/接线生","Reception/Telephonist",""));
        OPT_MAP_POSITION.put(3607,OptionMap.setMap("服务员/侍者/门童","Waiter/waitress",""));
        OPT_MAP_POSITION.put(3608,OptionMap.setMap("高级厨师","Senior chef",""));
        OPT_MAP_POSITION.put(3609,OptionMap.setMap("西式面点师/烹调师","Western-style flour dim sum teacher/Western Cooker",""));
        OPT_MAP_POSITION.put(3610,OptionMap.setMap("中式面点师/烹调师","Chinese type flour dim sum teacher/Chinese Cooker",""));
        OPT_MAP_POSITION.put(3611,OptionMap.setMap("调酒师/茶艺师","Wine mixer/Tea Specialist",""));
        OPT_MAP_POSITION.put(3612,OptionMap.setMap("娱乐/餐饮管理员","Entertainment/dining Manager",""));
        OPT_MAP_POSITION.put(3613,OptionMap.setMap("导游","Cicerone",""));
        OPT_MAP_POSITION.put(3614,OptionMap.setMap("旅游管理","Traveling management",""));
        OPT_MAP_POSITION.put(3615,OptionMap.setMap("客房主管/文员","Guest Room Manager/Service",""));
        OPT_MAP_POSITION.put(3616,OptionMap.setMap("公关主任","Public relations director",""));
        OPT_MAP_POSITION.put(3617,OptionMap.setMap("培训主任","Trains director",""));
        OPT_MAP_POSITION.put(3618,OptionMap.setMap("外联/计调（旅行社）","External Linker/Plan Adjustor (Travel Agency)",""));
        OPT_MAP_POSITION.put(3619,OptionMap.setMap("部长/领班/服务员","Minister/Service Supervisor/Service Waiter",""));
        OPT_MAP_POSITION.put(3699,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(3700,OptionMap.setMap("包装/印刷/纸品类","Printing/Packaging/Paper",""));
        OPT_MAP_POSITION.put(3701,OptionMap.setMap("包装工程师","Packs Engineer",""));
        OPT_MAP_POSITION.put(3702,OptionMap.setMap("调墨技师","Adjusts the Mexican technician",""));
        OPT_MAP_POSITION.put(3703,OptionMap.setMap("单色机长","Singles-colorprinting Machine Operator",""));
        OPT_MAP_POSITION.put(3704,OptionMap.setMap("罗兰机机长","Roland Machine Operator",""));
        OPT_MAP_POSITION.put(3705,OptionMap.setMap("印刷工程师","Printing Engineer",""));
        OPT_MAP_POSITION.put(3706,OptionMap.setMap("折页机长","Page-Folding Printing Machine Operator",""));
        OPT_MAP_POSITION.put(3707,OptionMap.setMap("过胶机机长","Gelatinizing Machine Operator",""));
        OPT_MAP_POSITION.put(3708,OptionMap.setMap("切纸机机长","Paper Cutting Machine Operator",""));
        OPT_MAP_POSITION.put(3709,OptionMap.setMap("啤机机长","Injection Machine Operator",""));
        OPT_MAP_POSITION.put(3710,OptionMap.setMap("UV机机长","UV Machine Operator",""));
        OPT_MAP_POSITION.put(3711,OptionMap.setMap("纸闸机机长","Paper-brake Machine Operator",""));
        OPT_MAP_POSITION.put(3712,OptionMap.setMap("骑马钉机长","Saddle-stitched Machine Operator",""));
        OPT_MAP_POSITION.put(3713,OptionMap.setMap("排书机机长","Book-arraging Machine Operator",""));
        OPT_MAP_POSITION.put(3714,OptionMap.setMap("工艺开单员/工艺工程师","Craftwork Biller/Craftwork Engineeer",""));
        OPT_MAP_POSITION.put(3715,OptionMap.setMap("设计制版/排版/组版","Design Platemaker/Typesetter/Assembler",""));
        OPT_MAP_POSITION.put(3716,OptionMap.setMap("凹版印刷技术员","Intaglio Printing Technician",""));
        OPT_MAP_POSITION.put(3717,OptionMap.setMap("丝印机长/主管","Screen Printing Operator/Supervisor",""));
        OPT_MAP_POSITION.put(3718,OptionMap.setMap("菲林输出","Film Printing",""));
        OPT_MAP_POSITION.put(3719,OptionMap.setMap("水印印刷","Watermark Printing",""));
        OPT_MAP_POSITION.put(3720,OptionMap.setMap("晒版技工","Plate Copying Technician",""));
        OPT_MAP_POSITION.put(3721,OptionMap.setMap("单面/双面瓦楞纸机长","Single-side/Double-side Corrugated Paper Machine Operator",""));
        OPT_MAP_POSITION.put(3722,OptionMap.setMap("制浆造纸工程师","Papermaking Engineer",""));
        OPT_MAP_POSITION.put(3723,OptionMap.setMap("裱纸/分纸/印唛/烫金","Paper Coating/Paper Dispart/Icon Printing/ Gilding Press Technician",""));
        OPT_MAP_POSITION.put(3724,OptionMap.setMap("打稿师傅","Draft Operator",""));
        OPT_MAP_POSITION.put(3725,OptionMap.setMap("双色机长","Two-tone Operator",""));
        OPT_MAP_POSITION.put(3726,OptionMap.setMap("打钉机长","Nailing Chargeman",""));
        OPT_MAP_POSITION.put(3799,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(3800,OptionMap.setMap("服装纺织/鞋帽/皮革类","Apparel/Shoes & Hats/Leather Goods",""));
        OPT_MAP_POSITION.put(3801,OptionMap.setMap("服装设计师","Apparel Designer",""));
        OPT_MAP_POSITION.put(3802,OptionMap.setMap("手袋设计","Handbag Design",""));
        OPT_MAP_POSITION.put(3803,OptionMap.setMap("皮具开发设计","Leather Goods Design",""));
        OPT_MAP_POSITION.put(3804,OptionMap.setMap("染整工程师","Printing and dyeing",""));
        OPT_MAP_POSITION.put(3805,OptionMap.setMap("制版师","Apparels Sample Production",""));
        OPT_MAP_POSITION.put(3806,OptionMap.setMap("纸样师","Paper Sample",""));
        OPT_MAP_POSITION.put(3807,OptionMap.setMap("制鞋","Shoemaking",""));
        OPT_MAP_POSITION.put(3808,OptionMap.setMap("调色员","Mixes colors",""));
        OPT_MAP_POSITION.put(3809,OptionMap.setMap("面辅料采购","Fabric excipients",""));
        OPT_MAP_POSITION.put(3810,OptionMap.setMap("计量员","Measurement",""));
        OPT_MAP_POSITION.put(3811,OptionMap.setMap("打版师","Apparel Sample Technician",""));
        OPT_MAP_POSITION.put(3812,OptionMap.setMap("机织车缝工艺员","Sewing Craftman for Weave Machine",""));
        OPT_MAP_POSITION.put(3813,OptionMap.setMap("吓数师傅","Sweater messurement master",""));
        OPT_MAP_POSITION.put(3814,OptionMap.setMap("出格师傅","Shoe Tree Design",""));
        OPT_MAP_POSITION.put(3815,OptionMap.setMap("板房师傅","Sample master",""));
        OPT_MAP_POSITION.put(3816,OptionMap.setMap("面部/底部技工","Surface / bottom mechanic",""));
        OPT_MAP_POSITION.put(3817,OptionMap.setMap("面部/底部全套","A full set of surface / bottom",""));
        OPT_MAP_POSITION.put(3818,OptionMap.setMap("大底技术员","Outsole technician",""));
        OPT_MAP_POSITION.put(3819,OptionMap.setMap("大底磨边","Sole edge grinding",""));
        OPT_MAP_POSITION.put(3820,OptionMap.setMap("面版师","Surface sample master",""));
        OPT_MAP_POSITION.put(3821,OptionMap.setMap("底版师","Bottom sample master",""));
        OPT_MAP_POSITION.put(3822,OptionMap.setMap("裁断机手","Cutting machine master",""));
        OPT_MAP_POSITION.put(3823,OptionMap.setMap("针车技工","Needle machine mechanic",""));
        OPT_MAP_POSITION.put(3824,OptionMap.setMap("针车品检","Needle machine inspection",""));
        OPT_MAP_POSITION.put(3825,OptionMap.setMap("成型干部","Molding cadres",""));
        OPT_MAP_POSITION.put(3826,OptionMap.setMap("鞋楦技术员","Shoe tree technician",""));
        OPT_MAP_POSITION.put(3827,OptionMap.setMap("面部针车熟手","Surface needle machine proficient",""));
        OPT_MAP_POSITION.put(3828,OptionMap.setMap("针车机修","Needle machine repair",""));
        OPT_MAP_POSITION.put(3829,OptionMap.setMap("鞋样电脑设计","Shoe pattern design",""));
        OPT_MAP_POSITION.put(3830,OptionMap.setMap("放码技工","Set size mechanic",""));
        OPT_MAP_POSITION.put(3831,OptionMap.setMap("抓色技术员","Grasping color technician",""));
        OPT_MAP_POSITION.put(3832,OptionMap.setMap("服装纸样版师","Clothing pattern master",""));
        OPT_MAP_POSITION.put(3833,OptionMap.setMap("成型品检","Molding inspection",""));
        OPT_MAP_POSITION.put(3834,OptionMap.setMap("底材仓库全检","Bottom material warehouse inspection",""));
        OPT_MAP_POSITION.put(3835,OptionMap.setMap("层皮跟品检","Skin heel inspection",""));
        OPT_MAP_POSITION.put(3836,OptionMap.setMap("样品跟单员","Sample Merchandiser",""));
        OPT_MAP_POSITION.put(3837,OptionMap.setMap("尾部技工","Tail mechanic",""));
        OPT_MAP_POSITION.put(3838,OptionMap.setMap("中烫/大烫技工","Semi/finish clothes ironing mechanic",""));
        OPT_MAP_POSITION.put(3839,OptionMap.setMap("开版师/版房技术员","Sample mechanic",""));
        OPT_MAP_POSITION.put(3840,OptionMap.setMap("跟单员","Order Clerk",""));
        OPT_MAP_POSITION.put(3899,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(3900,OptionMap.setMap("超市/商场/零售/连锁类","Supermarket/Shops/Retail",""));
        OPT_MAP_POSITION.put(3901,OptionMap.setMap("营业员/服务员/店员","Shop assistant/counterjumper",""));
        OPT_MAP_POSITION.put(3902,OptionMap.setMap("导购员","Phasing leader",""));
        OPT_MAP_POSITION.put(3903,OptionMap.setMap("收银员","Gathering",""));
        OPT_MAP_POSITION.put(3904,OptionMap.setMap("店长","Innkeeper/shop manager",""));
        OPT_MAP_POSITION.put(3905,OptionMap.setMap("防损员","Loss Prevention Management",""));
        OPT_MAP_POSITION.put(3906,OptionMap.setMap("营销主管","Marketing director",""));
        OPT_MAP_POSITION.put(3907,OptionMap.setMap("理货员","Tally clerk",""));
        OPT_MAP_POSITION.put(3908,OptionMap.setMap("陈列员/陈列展示","Exhibition demonstrated",""));
        OPT_MAP_POSITION.put(3909,OptionMap.setMap("连锁管理","Chain management",""));
        OPT_MAP_POSITION.put(3910,OptionMap.setMap("专卖店/加盟店管理","Exclusive agency/alliance shop management",""));
        OPT_MAP_POSITION.put(3911,OptionMap.setMap("市场督导/调查","Market director/investigation",""));
        OPT_MAP_POSITION.put(3912,OptionMap.setMap("生鲜/干（杂）货管理","Raw Food/Dry (Mixed) Goods Management",""));
        OPT_MAP_POSITION.put(3913,OptionMap.setMap("货品配送","Goods Allocation",""));
        OPT_MAP_POSITION.put(3999,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(4000,OptionMap.setMap("技工/普工类","Mechanic/General worker",""));
        OPT_MAP_POSITION.put(4001,OptionMap.setMap("叉车司机","Forklift Worker",""));
        OPT_MAP_POSITION.put(4002,OptionMap.setMap("电工","Electrician",""));
        OPT_MAP_POSITION.put(4003,OptionMap.setMap("焊工","Weld",""));
        OPT_MAP_POSITION.put(4004,OptionMap.setMap("车床工","Latheg",""));
        OPT_MAP_POSITION.put(4005,OptionMap.setMap("铣、刨、钣、铆、冲、铸","Planing,Francium,Rivetting,Washing,Cast",""));
        OPT_MAP_POSITION.put(4006,OptionMap.setMap("钳工","Pincers",""));
        OPT_MAP_POSITION.put(4007,OptionMap.setMap("裁、剪、车","Sewing",""));
        OPT_MAP_POSITION.put(4008,OptionMap.setMap("缝、慰、烫","Iron",""));
        OPT_MAP_POSITION.put(4009,OptionMap.setMap("打磨、抛光","Grinding,Polishing",""));
        OPT_MAP_POSITION.put(4010,OptionMap.setMap("空调工/锅炉工/电梯工","Air-conditioning/temp/elevator work",""));
        OPT_MAP_POSITION.put(4011,OptionMap.setMap("汽车/摩托车维护员","Automotive Engineer",""));
        OPT_MAP_POSITION.put(4012,OptionMap.setMap("水工/木工/油漆工","Warterworker,Woodworker,Painter",""));
        OPT_MAP_POSITION.put(4013,OptionMap.setMap("锁具修理工","Lock repairman",""));
        OPT_MAP_POSITION.put(4014,OptionMap.setMap("普通工人","General worker",""));
        OPT_MAP_POSITION.put(4015,OptionMap.setMap("技师","Technician",""));
        OPT_MAP_POSITION.put(4016,OptionMap.setMap("模具工","Mold Engineer",""));
        OPT_MAP_POSITION.put(4099,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(4100,OptionMap.setMap("轻工/陶瓷类","Light industry/Ceramics",""));
        OPT_MAP_POSITION.put(4101,OptionMap.setMap("包装工程师","Packs Engineer",""));
        OPT_MAP_POSITION.put(4102,OptionMap.setMap("服装纺织工","Accouterments/Spin",""));
        OPT_MAP_POSITION.put(4103,OptionMap.setMap("物料经理","Material Manager",""));
        OPT_MAP_POSITION.put(4104,OptionMap.setMap("物料主管/专员","Material Manager/Special Commissioner",""));
        OPT_MAP_POSITION.put(4105,OptionMap.setMap("印刷/染整技术员","Press/printing and dyeing",""));
        OPT_MAP_POSITION.put(4106,OptionMap.setMap("调色员","Mixes colors",""));
        OPT_MAP_POSITION.put(4107,OptionMap.setMap("纸浆造纸工艺","Paper making",""));
        OPT_MAP_POSITION.put(4108,OptionMap.setMap("制鞋/制衣/制革/手袋","Shoemaking/Clothing/Curry/Vanity",""));
        OPT_MAP_POSITION.put(4109,OptionMap.setMap("面料辅料开发/采购专员","Fabric excipients Development/Procurement Commissioner",""));
        OPT_MAP_POSITION.put(4110,OptionMap.setMap("板房/楦头/底格出格师","Shoe Tree Design",""));
        OPT_MAP_POSITION.put(4111,OptionMap.setMap("服装打样/制版工","Apparels Sample Production",""));
        OPT_MAP_POSITION.put(4112,OptionMap.setMap("车板工","Paper Sample",""));
        OPT_MAP_POSITION.put(4113,OptionMap.setMap("裁床工","Cuts the bed labor",""));
        OPT_MAP_POSITION.put(4114,OptionMap.setMap("食品工程/糖酒饮料/粮油副食","Foodstuff Engineering/Candy/Wine/Drink/Grain/oil",""));
        OPT_MAP_POSITION.put(4115,OptionMap.setMap("金银首饰加工","Jewellery process",""));
        OPT_MAP_POSITION.put(4116,OptionMap.setMap("陶瓷设计师","Ceramic Designer",""));
        OPT_MAP_POSITION.put(4117,OptionMap.setMap("陶瓷选料","Ceramic Material Selector",""));
        OPT_MAP_POSITION.put(4118,OptionMap.setMap("陶瓷化验","Ceramic Tester",""));
        OPT_MAP_POSITION.put(4119,OptionMap.setMap("陶瓷手工成型","Ceramic Handworker",""));
        OPT_MAP_POSITION.put(4120,OptionMap.setMap("瓷片技术员","Porcelain Technician",""));
        OPT_MAP_POSITION.put(4121,OptionMap.setMap("陶瓷抛光工","Ceramic Furbisher",""));
        OPT_MAP_POSITION.put(4122,OptionMap.setMap("陶瓷刮平工","Ceramic Technician",""));
        OPT_MAP_POSITION.put(4123,OptionMap.setMap("陶瓷印花","Ceramic Printing",""));
        OPT_MAP_POSITION.put(4124,OptionMap.setMap("陶瓷彩绘员","Ceramic Colored Drawing Worker",""));
        OPT_MAP_POSITION.put(4125,OptionMap.setMap("陶瓷喷釉","Ceramic Spray Glazer",""));
        OPT_MAP_POSITION.put(4126,OptionMap.setMap("陶瓷装罐工","Ceramic Worker",""));
        OPT_MAP_POSITION.put(4127,OptionMap.setMap("计量员","Counter",""));
        OPT_MAP_POSITION.put(4128,OptionMap.setMap("窑炉技术员","Stove Technician",""));
        OPT_MAP_POSITION.put(4199,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(4200,OptionMap.setMap("贸易/采购/物流类","Distribution/Purchasing",""));
        OPT_MAP_POSITION.put(4201,OptionMap.setMap("物流操作员","Logistics operator",""));
        OPT_MAP_POSITION.put(4202,OptionMap.setMap("物流专员/助理","Logistics Commissioner/Assistant",""));
        OPT_MAP_POSITION.put(4203,OptionMap.setMap("物流调度员","Logistics Dispatcher",""));
        OPT_MAP_POSITION.put(4204,OptionMap.setMap("物流总监/经理/主管","Logistics Director/Manager/Director",""));
        OPT_MAP_POSITION.put(4205,OptionMap.setMap("单证员","Order Clerk",""));
        OPT_MAP_POSITION.put(4206,OptionMap.setMap("快递员","Courier",""));
        OPT_MAP_POSITION.put(4207,OptionMap.setMap("理货员","Tally man",""));
        OPT_MAP_POSITION.put(4208,OptionMap.setMap("运输经理/主管","Transit Manager/Directer",""));
        OPT_MAP_POSITION.put(4209,OptionMap.setMap("货运代理","Freight forwarders",""));
        OPT_MAP_POSITION.put(4210,OptionMap.setMap("集装箱业务","Container service",""));
        OPT_MAP_POSITION.put(4211,OptionMap.setMap("仓库经理/主管","Storage manager/director",""));
        OPT_MAP_POSITION.put(4212,OptionMap.setMap("仓库管理员","Storage clerk",""));
        OPT_MAP_POSITION.put(4213,OptionMap.setMap("供应链总监","Supply Chain Director",""));
        OPT_MAP_POSITION.put(4214,OptionMap.setMap("供应链经理/主管","Supply chain Manager/Supervisor",""));
        OPT_MAP_POSITION.put(4215,OptionMap.setMap("供应链专员","Supply chain special Commissioner",""));
        OPT_MAP_POSITION.put(4216,OptionMap.setMap("注册职业采购经理（CPPM）","Registered occupational Procurement Manager(CPPM)",""));
        OPT_MAP_POSITION.put(4217,OptionMap.setMap("采购经理/主管","Procurement Manager/Supervisor",""));
        OPT_MAP_POSITION.put(4218,OptionMap.setMap("采购专员/助理","Procurement Commissioner/Assistant",""));
        OPT_MAP_POSITION.put(4219,OptionMap.setMap("采购管理员","Stock Management",""));
        OPT_MAP_POSITION.put(4220,OptionMap.setMap("国际业务","International business",""));
        OPT_MAP_POSITION.put(4221,OptionMap.setMap("外贸经理/主管","Foreign Trade Manager/Supervisor",""));
        OPT_MAP_POSITION.put(4222,OptionMap.setMap("外贸专员/助理","Foreign Trade Commissioner/Assistant",""));
        OPT_MAP_POSITION.put(4223,OptionMap.setMap("国内贸易人员","Domestic trade personnel",""));
        OPT_MAP_POSITION.put(4224,OptionMap.setMap("业务跟单员","Service freight bill",""));
        OPT_MAP_POSITION.put(4225,OptionMap.setMap("外销员","Export commissioner",""));
        OPT_MAP_POSITION.put(4226,OptionMap.setMap("报关员","Customs commissioner",""));
        OPT_MAP_POSITION.put(4227,OptionMap.setMap("船务人员","Shipman",""));
        OPT_MAP_POSITION.put(4299,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(4300,OptionMap.setMap("后勤保障类","Logistics/Safeguard",""));
        OPT_MAP_POSITION.put(4301,OptionMap.setMap("保安队长","Security captain",""));
        OPT_MAP_POSITION.put(4302,OptionMap.setMap("保安","Security",""));
        OPT_MAP_POSITION.put(4303,OptionMap.setMap("司机","Chauffeur",""));
        OPT_MAP_POSITION.put(4304,OptionMap.setMap("消防","Firemen",""));
        OPT_MAP_POSITION.put(4305,OptionMap.setMap("社区服务","Community services",""));
        OPT_MAP_POSITION.put(4306,OptionMap.setMap("清洁工/后勤","Dustman/logistics",""));
        OPT_MAP_POSITION.put(4307,OptionMap.setMap("食堂主管/经理","Canteen Supervisor/Manager",""));
        OPT_MAP_POSITION.put(4308,OptionMap.setMap("食堂厨师","Refectory chef",""));
        OPT_MAP_POSITION.put(4309,OptionMap.setMap("搬运","Portage",""));
        OPT_MAP_POSITION.put(4310,OptionMap.setMap("寻呼/声讯","Pagers/Voice information services",""));
        OPT_MAP_POSITION.put(4311,OptionMap.setMap("保姆/钟点工","Nanny/Hour Labor",""));
        OPT_MAP_POSITION.put(4399,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(4400,OptionMap.setMap("出版/发行类","Edit/Publish",""));
        OPT_MAP_POSITION.put(4401,OptionMap.setMap("总编/副总编","Editor-in-chief/Subeditor",""));
        OPT_MAP_POSITION.put(4402,OptionMap.setMap("发行主管/助理","Dispatch Manager/Assistant",""));
        OPT_MAP_POSITION.put(4403,OptionMap.setMap("编辑主任","Edit Director",""));
        OPT_MAP_POSITION.put(4404,OptionMap.setMap("撰稿人","Copywriter",""));
        OPT_MAP_POSITION.put(4405,OptionMap.setMap("采访主任","Interviews Director",""));
        OPT_MAP_POSITION.put(4406,OptionMap.setMap("美术编辑","Art Editor",""));
        OPT_MAP_POSITION.put(4407,OptionMap.setMap("排版设计","Layout Designer",""));
        OPT_MAP_POSITION.put(4408,OptionMap.setMap("校对/录入","Proofreader/Data Entry Staff",""));
        OPT_MAP_POSITION.put(4409,OptionMap.setMap("出版/发行","Publishing/Distribution",""));
        OPT_MAP_POSITION.put(4410,OptionMap.setMap("文字/摄影记者","Writing/Photo Journalist",""));
        OPT_MAP_POSITION.put(4411,OptionMap.setMap("编辑","Edit",""));
        OPT_MAP_POSITION.put(4499,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(4500,OptionMap.setMap("翻译语言类","Translation",""));
        OPT_MAP_POSITION.put(4501,OptionMap.setMap("英语翻译","English",""));
        OPT_MAP_POSITION.put(4502,OptionMap.setMap("日语翻译","Japanese",""));
        OPT_MAP_POSITION.put(4503,OptionMap.setMap("法语翻译","French",""));
        OPT_MAP_POSITION.put(4504,OptionMap.setMap("德语翻译","German",""));
        OPT_MAP_POSITION.put(4505,OptionMap.setMap("俄语翻译","Russian",""));
        OPT_MAP_POSITION.put(4506,OptionMap.setMap("朝鲜语翻译","Korea",""));
        OPT_MAP_POSITION.put(4507,OptionMap.setMap("越南语","Vietnamese",""));
        OPT_MAP_POSITION.put(4508,OptionMap.setMap("西班牙语翻译","Spanish",""));
        OPT_MAP_POSITION.put(4509,OptionMap.setMap("意大利语翻译","Italian",""));
        OPT_MAP_POSITION.put(4510,OptionMap.setMap("阿拉伯语翻译","Arabic",""));
        OPT_MAP_POSITION.put(4511,OptionMap.setMap("中国方言翻译","Chinese dialect translation",""));
        OPT_MAP_POSITION.put(4599,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(4600,OptionMap.setMap("汽车类","Automotive",""));
        OPT_MAP_POSITION.put(4601,OptionMap.setMap("汽车机构工程师","Automotive Structural Engineer",""));
        OPT_MAP_POSITION.put(4602,OptionMap.setMap("汽车设计工程师","Automotive Design Engineer",""));
        OPT_MAP_POSITION.put(4603,OptionMap.setMap("汽车电子工程师","Automotive Electronics Engineer",""));
        OPT_MAP_POSITION.put(4604,OptionMap.setMap("汽车质量管理","Automotive Quality Management",""));
        OPT_MAP_POSITION.put(4605,OptionMap.setMap("汽车安全性能工程师","Safety Performance Engineer",""));
        OPT_MAP_POSITION.put(4606,OptionMap.setMap("汽车装配工艺工程师","Assembly Process Engineer",""));
        OPT_MAP_POSITION.put(4607,OptionMap.setMap("汽车修理人员","Automotive Repair",""));
        OPT_MAP_POSITION.put(4608,OptionMap.setMap("4S店经理/维修站经理","4S Shop Manager/Maintenance Station Manager",""));
        OPT_MAP_POSITION.put(4609,OptionMap.setMap("汽车销售/经纪人","Automotive Sales Consultant/Brokers",""));
        OPT_MAP_POSITION.put(4610,OptionMap.setMap("二手车评估师","Second-Hand Car Appraisers",""));
        OPT_MAP_POSITION.put(4611,OptionMap.setMap("汽车美容","Automotive Cosmetology",""));
        OPT_MAP_POSITION.put(4699,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(4700,OptionMap.setMap("家具类","Furniture",""));
        OPT_MAP_POSITION.put(4701,OptionMap.setMap("家具设计","Furniture Design",""));
        OPT_MAP_POSITION.put(4702,OptionMap.setMap("家具油漆工/主管","Furniture Paint supervisor/Directer",""));
        OPT_MAP_POSITION.put(4703,OptionMap.setMap("家具木工/主管","Furniture Carpentry/Directer",""));
        OPT_MAP_POSITION.put(4704,OptionMap.setMap("弯管师傅","Bend Master",""));
        OPT_MAP_POSITION.put(4705,OptionMap.setMap("家具打磨/打样","Furniture Proofing/Polished",""));
        OPT_MAP_POSITION.put(4706,OptionMap.setMap("家具备料/开料/精裁","Furniture Preparation/Kai Liao/Fine cut",""));
        OPT_MAP_POSITION.put(4707,OptionMap.setMap("实木封边/压木","Solid Edge/Pressure veneer",""));
        OPT_MAP_POSITION.put(4799,OptionMap.setMap("其它","Other",""));
        OPT_MAP_POSITION.put(9900,OptionMap.setMap("其它岗位类","Others",""));
        OPT_MAP_POSITION.put(9901,OptionMap.setMap("航空航天","Aerospace",""));
        OPT_MAP_POSITION.put(9902,OptionMap.setMap("交通运输","Traffic",""));
        OPT_MAP_POSITION.put(9903,OptionMap.setMap("声光技术","Voice/Light tech.",""));
        OPT_MAP_POSITION.put(9904,OptionMap.setMap("生物技术","Boilogy tech.",""));
        OPT_MAP_POSITION.put(9905,OptionMap.setMap("测绘技术","Mapping tech.",""));
        OPT_MAP_POSITION.put(9906,OptionMap.setMap("激光技术","Laser tech.",""));
        OPT_MAP_POSITION.put(9907,OptionMap.setMap("地质勘探","Geology prove",""));
        OPT_MAP_POSITION.put(9908,OptionMap.setMap("矿产治金","Mine/metallurgy",""));
        OPT_MAP_POSITION.put(9909,OptionMap.setMap("环境工程","Environment engineering",""));
        OPT_MAP_POSITION.put(9910,OptionMap.setMap("农、林、牧、渔","Farming/Lumber/Pasturage/Fishery",""));
        OPT_MAP_POSITION.put(9911,OptionMap.setMap("市政建设/城市规划","Municipal Construction/Urban Design & Planning",""));
        OPT_MAP_POSITION.put(9999,OptionMap.setMap("其它","Other",""));
        fillBigSmallMap();
    }

    /**
     * 填充大类列表，以及大小类对应关系的map
     */
   private static void fillBigSmallMap(){
       Map<Integer,List<Map<String,String>>> tempBigSmalMap = Maps.newHashMap();
       List<Map<String,String>> OPT_LIST_BIG_TEMP = Lists.newArrayList();
       for(Map.Entry<Integer,Map<String,String>> entry : OPT_MAP_POSITION.entrySet()){
           Integer code =Integer.parseInt((entry.getKey()+"").substring(0,2));//获取代码
           if(StringUtils.endsWith(OptionMap.getCityCodeBits(entry.getKey()), "00")){//是否大类代码
               Map<String, String> tempMapCity = entry.getValue();
               Map<String, String> result = Maps.newHashMap(tempMapCity);
               result.put("code",entry.getKey()+"");
               result.put("hasChild","1");
               OPT_LIST_BIG_TEMP.add(result);
           }else{
               List<Map<String,String>> tempList = tempBigSmalMap.get(code);
               if(tempBigSmalMap.get(code) == null){
                   tempList = Lists.newArrayList();
                   tempBigSmalMap.put(code, tempList);
               }
               Map<String, String> tempMapSmall = entry.getValue();
               Map<String, String> result = Maps.newHashMap(tempMapSmall);
               result.put("code",entry.getKey()+"");
               result.put("hasChild","0");
               tempList.add(result);
           }
       }
       OPT_MAP_BIG_SMALL_CITY = ImmutableMap.copyOf(tempBigSmalMap);
       OPT_LIST_BIG =  ImmutableList.copyOf(OPT_LIST_BIG_TEMP);

   }

    @SuppressWarnings({"rawtypes", "unchecked"})
    public static Integer getKeyByValueAndType(String value,String type) {
        Map map = OPT_MAP_POSITION;
        for (Object obj : map.keySet()) {
            Integer key = (Integer) obj;
            Map<String, String> valueMap = (Map<String, String>) map.get(key);
            if (StringUtils.equals(value, valueMap.get(type))) {
                return key;
            }
        }
        return null;
    }

}
